LITRiview/src/LITReview/urls.py
from django.contrib import admin
from django.urls import path
from login import views
import flow.views
import abo.views
import post.views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.login_page, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('accueil/', flow.views.accueil, name='accueil'),
    path('creation_de_compte', views.creation_compte, name ="creation_compte" ),
    path('posts/', flow.views.accueil, name='posts'),
    path('abonnement/', flow.views.accueil, name='abonnement'),
    path('demander_critique/', flow.views.demander_critique, name='demander_critique'),
    path('creer_critique/', flow.views.creer_critique, name='creer_critique'),
    path('creer_critique_rep_demande/', flow.views.reponse_demande_critique, name='creer_critique_rep_demande'),
    path('abonnements/', abo.views.abonnement, name='abonnements'),
    path('posts-user/', post.views.post_user, name='posts-user'),
    path('unfollow/', abo.views.unfollow, name ="unfollow"),
    path('follow/', abo.views.follow, name ="follow"),
    path('modifier/', post.views.modify_deleted, name = "modify_deleted"),
    path('enregister_modifications/', post.views.register_modifications, name ="register_modifications")
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LITRiview/src/post/models.py
from django.db import models

# Create your models here.

LITRiview/src/flow/forms.py
from django import forms
from django.forms import ModelForm
from flow.models import DemanderCritiqueMod, CreerCritiqueMod

class DemanderCritiqueForm(ModelForm):

    titre_demande = forms.CharField(max_length=63, label="Titre")
    description = forms.CharField(max_length=63, label="Description")
    img_livre = forms.ImageField(label="Image")

    class Meta:

        model = DemanderCritiqueMod
        fields = ('titre_demande', 'description', 'img_livre')

class CreerCritiqueForm(ModelForm):

    titre_creer = forms.CharField(max_length=100 , label='Titre') 
    note = forms.CheckboxInput()
    commentaire = forms.CharField(max_length=600, label='Commentaire')
    
    class Meta:
        model = CreerCritiqueMod
        fields = ('titre_creer', 'note', 'commentaire')

LITRiview/src/post/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from flow.models import CreerCritiqueMod, DemanderCritiqueMod
from flow.forms import CreerCritiqueForm, DemanderCritiqueForm

# Create your views here.
@login_required
def post_user(request):
    """Recupération des posts de l'utilisateur"""
    critique_crees = CreerCritiqueMod.objects.all()
    critique_demandees = DemanderCritiqueMod.objects.all()
    user = request.user 
    liste_critique_crees = []
    liste_critique_demandees = []

    #récupération des critique crées par l'utilisateur
    for i in range(len(critique_crees)): 
        if user.username == critique_crees[i].createur.username:
            liste_critique_crees.append(critique_crees[i])

    #Récupération des demandes de critique crées par l'utilisateur
    for j in range(len(critique_demandees)): 
        if user.username == critique_demandees[j].createur.username:
            liste_critique_demandees.append(critique_demandees[j])
        

     
    return render(request, 'posts.html', context={ 'user' : user, 'liste_critique_crees' : liste_critique_crees, 'liste_critique_demandees' : liste_critique_demandees, 'critique_demandee' : critique_demandees})

@login_required
def modify_deleted(request):
    """Récupérer les données à modifier, permettre de supprimer un ticlet"""
    
    user_on = request.user
    critique_demandees = DemanderCritiqueMod.objects.all()
    critique_cree = CreerCritiqueMod.objects.all()
    

    if 'modify_btn_demande' in request.POST :
        post_id = request.POST.get('modify_btn_demande', None)

        #récupération des infos de la critiqué demandée que l'on souhaite modifier
        for critique in critique_demandees:
            if critique.id == int(post_id):
                data = {
                    'titre_demande' : critique.titre,
                    'description' : critique.description,
                    'img_livre' :  critique.img_livre
                   
                }

                form = DemanderCritiqueForm(initial=data)

                
                return render(request, 'modify.html', context={'form' : form, 'critique_demandee' : critique , 'data' : data})

    if 'deleted_btn_demande' in request.POST : 

        post_id = request.POST.get('deleted_btn_demande', None)

        #Supression de la demande de critique
        for critique in critique_demandees:
            if critique.id == int(post_id):
                critique.delete()
                redirect('posts-user')
    
    if 'modify_btn_cree' in request.POST :

        post_id = request.POST.get('modify_btn_cree', None)
       
        #récupération des infos de la demande de critique lié à notre critique
        for critique in critique_cree:
            if critique.id == int(post_id):
                data = {
                    'titre_creer' : critique.titre,
                    'note' : critique.note,
                    'commentaire' :  critique.commentaire
                }

                form = CreerCritiqueForm(initial=data)

        #récupération des infos de la critique que l'on souhaite modifier
        for critique in critique_demandees: 
                if  critique.reponse_critique != None:
                    if int(post_id) == critique.reponse_critique.id:
                        critique_demandee = critique
                        break

                
        return render(request, 'modify.html', context={'form' : form, 'critique_demandee' : critique_demandee})

    if 'deleted_btn_cree' in request.POST : 
        post_id = request.POST.get('deleted_btn_cree', None)

        #Suppression de la critique créée
        for critique in critique_cree:
            if critique.id == int(post_id):
                critique.delete()
                redirect('posts-user')
        
 


    return redirect('posts-user')

@login_required
def register_modifications(request):
    """enregistrement des modifications"""

    if 'btn_register_creer' in request.POST : 
        id_critique_modif = request.POST.get('btn_register_creer',None)
        news_informations_forms = CreerCritiqueForm()
        new_informations_Mod = CreerCritiqueMod.objects.all()

        #récupération de la critique créée que l'on souhaite modifier
        for data in new_informations_Mod:
            if int(id_critique_modif) == data.id:
                new_informations_Mod = data
                break

        #Sauvegarde des modifications
        if request.method == "POST":
            if news_informations_forms.is_valid:
                news_informations_forms = CreerCritiqueForm(request.POST)
                new_informations_Mod.titre = news_informations_forms.data['titre_creer']
                new_informations_Mod.note = news_informations_forms.data['note']
                new_informations_Mod.commentaire = news_informations_forms.data['commentaire']

                new_informations_Mod.save()

    elif 'btn_register_demandee' in request.POST : 

        id_critique_modif = request.POST.get('btn_register_demandee',None)
        news_informations_forms = DemanderCritiqueForm()
        new_informations_Mod = DemanderCritiqueMod.objects.all()

        #récupération de la demande de critique que l'on souhaite modifier
        for data in new_informations_Mod:
            if int(id_critique_modif) == data.id:
                new_informations_Mod = data
                break

        #Sauvegarde des modifications
        if request.method == "POST":
            if news_informations_forms.is_valid:
                news_informations_forms = DemanderCritiqueForm(request.POST, request.FILES)
                new_informations_Mod.titre = news_informations_forms.data['titre_demande']
                new_informations_Mod.description = news_informations_forms.data['description']
                if len(news_informations_forms.files) != 0:
                    new_informations_Mod.img_livre = news_informations_forms.files['img_livre']

                new_informations_Mod.save()


    return redirect('posts-user')

    

LITRiview/src/post/templates/modify.html
{% extends 'base_flow.html' %}
{% block content %}
<div class="main-container-modify">
    <h2> modification de la publication</h2>
    {% if critique_demandee.reponse_critique.id != None and form.img_livre == None %}
    <div class="ticket-demande">
            <p>Vous êtes en train de poster en réponse à</p>
            <form  method="POST" action="{% url 'register_modifications' %}" enctype="multipart/form-data", id="form_modif_rep_demande_critique">
                {% csrf_token %}
            <!--Affichage de la demande lié à la critique que l'on souhaite modifier-->
            <ul>
                <div class="ticket-elements">
                    <div class="main-elements">
                        <li>{{critique_demandee.titre}}</li>
                        <li>{{critique_demandee.description}}</li>
                        <li><img src="{{critique_demandee.img_livre.url}}"></li>
                    </div>
                    <div class="ticket-date">
                        <li>{{critique_demandee.date_creation}}</li>
                    </div>
                </div>
            </ul>
    </div>
    <!--Critique que l'on souhaite modifier-->
    <div class = "answer-ticket">
        <p>Critique</p>
            {{form.as_p}}
        <button type="submit" id="btn-register-change-place" class="btn-register-changes"  form="form_modif_rep_demande_critique" name="btn_register_creer" value ="{{critique_demandee.reponse_critique.id}}">Enregistrer</button>
        </form>
    </div>
    {% else %}
        <!--Demande de critique que l'on souhaite modifier-->
        <form  method="POST" action="{% url 'register_modifications' %}" enctype="multipart/form-data", id="form_modif_rep_demande_critique">
            <p>
                <label for="id_titre_demande">Titre</label>
                <input type="text" name="titre_demande" value="{{data.titre_demande}}" required id="id_titre_demande">
            </p>
            <p>
                <label for="id_description">Description</label>
                <input type="text" name="description" value="{{data.description}}" required id="id_description">
            </p>

            <p>
                <img src="{{data.img_livre.url}}">
                <label for="id_img_livre"></label>
                <input type="file" name="img_livre" accept="image/*" id="id_img_livre">
            </p>
            {% csrf_token %}
            
            <!-- {{form.as_p}} --> 
        
        <button type="submit" class="btn-register-changes" form="form_modif_rep_demande_critique" name="btn_register_demandee" value ="{{critique_demandee.id}}">Envoyer</button>
        </form>
    {% endif %}
</div>
{% endblock content %}

LITRiview/src/post/templates/posts.html
{% extends 'base_flow.html' %}
{% block content %}
<div id ="main-container-posts">
    <h1>Vos Posts : </h1>
        <!--Liste des demande de critique faite-->
        <ul>
            {% for critique in liste_critique_demandees %}
            <div class = "medium-container">
                <form action="{% url 'modify_deleted' %}" method="POST" id="form_modify_deleted_demande">    
                    {% csrf_token %}
                    <div class ="flex-mode">
                        <div class="other-elements">
                            <li>{{critique.createur}} a publié une critique</li>
                            <li>{{critique.titre}}</li>
                            <li><img src="{{critique.img_livre.url}}"></li>
                        </div>
                        <div class= "date_creation">
                            <li>{{critique.date_creation}}</li>
                        </div>
                    </div>
                <!--Ajout des boutons de suppression et modification-->
                <div class ="btn-mod-del-container">
                    <button type="submit" class="btn-mod-del" name="modify_btn_demande" value="{{critique.id}}" form = "form_modify_deleted_demande" >Modifier</button>
                    <button type="submit" class="btn-mod-del" name="deleted_btn_demande" value="{{critique.id}}" form = "form_modify_deleted_demande">Supprimer</button>
                </div>
                </form>
            </div>
            {% endfor %}
        </ul>
    <h2>critiques crées</h2>
        <!--Liste des critique créées-->
        <ul>
        {% for critique_cree in liste_critique_crees %}
        <div class = "medium-container">
            <form action="{% url 'modify_deleted' %}" method="POST" id="form_modify_deleted_cree">
                {% csrf_token %}
                <div class="flex-mode-third">
                    <div class="other-element-third">
                        <li>{{critique_cree.createur}} a publié une critique</li>
                        <li>{{critique_cree.titre}} - {{critique_cree.note}}</li>
                        <li>{{critique_cree.commentaire}}</li>
                    </div>
                    <div class="date_creation-third">
                        <li>{{critique_cree.date_creation}}</li>
                    </div>
                </div>
                {% for critique in critique_demandee%}
                    {% if critique.reponse_critique.id == critique_cree.id %}
                        <div class ="flex-mode-seconde">
                            <div class="other-elements-second">
                                <li>Ticket - {{critique.createur}}</li>
                                <li>{{critique.titre}}</li>
                                <li><img src="{{critique.img_livre.url}}"></li>
                            </div>
                            <div class= "date_creation">
                                 <li>{{critique.date_creation}}</li>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
                   
            <!--Ajout des boutons de suppression et modification-->
            <div class ="btn-mod-del-container">
                <button type="submit"  class="btn-mod-del" name="modify_btn_cree" value="{{critique_cree.id}}" form = "form_modify_deleted_cree" >Modifier</button>
                <button type="submit"  class="btn-mod-del" name="deleted_btn_cree" value="{{critique_cree.id}}" form = "form_modify_deleted_cree">Supprimer</button>
            </div>
        </form>
    </div>
        {% endfor %}
        </ul>
</div>
{% endblock content %}